cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'heroku'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'google-chrome'
cask 'google-drive'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'transmission'
cask 'typeit4me'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
